services:
  postgres:
    image: postgres:14.5
    command: ["postgres", "-c", "fsync=false", "-c", "full_page_writes=off"]
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile_prod
    command: bash -c "bundle exec puma -C config/puma.rb"
    env_file: ./.env
    volumes:
      - .:/app
    depends_on:
      - postgres
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
      